# Generated by Django 2.1.5 on 2022-02-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=500)),
                ('tag_environ', models.BooleanField(default=False)),
                ('tag_service', models.BooleanField(default=False)),
                ('tag_cost', models.BooleanField(default=False)),
                ('tag_skill', models.BooleanField(default=False)),
                ('tag_attitude', models.BooleanField(default=False)),
                ('comment_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('salon_id', models.AutoField(primary_key=True, serialize=False)),
                ('salon_name', models.CharField(max_length=50)),
                ('salon_address', models.CharField(max_length=100)),
                ('salon_rate', models.FloatField()),
                ('salon_avg_price', models.FloatField(default=0.0)),
                ('salon_busy', models.BooleanField(default=False)),
                ('tag', models.CharField(default='0', max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_type', models.IntegerField(default=0)),
                ('service_price', models.FloatField(default=0.0)),
                ('service_rate', models.FloatField(default=0.0)),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follows',
            name='salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Salon'),
        ),
        migrations.AddField(
            model_name='follows',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Service'),
        ),
        migrations.AddField(
            model_name='comment',
            name='salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Salon'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
