# Generated by Django 2.1.5 on 2022-03-19 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('salon_or_service_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=500)),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('tag_environ', models.BooleanField(default=False)),
                ('tag_service', models.BooleanField(default=False)),
                ('tag_cost', models.BooleanField(default=False)),
                ('tag_skill', models.BooleanField(default=False)),
                ('tag_attitude', models.BooleanField(default=False)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Follows',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('salon_id', models.AutoField(primary_key=True, serialize=False)),
                ('salon_name', models.CharField(max_length=50)),
                ('salon_address', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('salon_avg_price', models.FloatField(default=0.0)),
                ('salon_busy', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='salon_image/default.jpg', upload_to='salon_image')),
                ('phone', models.CharField(max_length=16)),
                ('open_time', models.CharField(default='10:00am-5:00pm', max_length=32)),
                ('slug', models.SlugField(blank=True)),
                ('good_env', models.BooleanField(default=False)),
                ('good_service', models.BooleanField(default=False)),
                ('cost_effective', models.BooleanField(default=False)),
                ('good_skill', models.BooleanField(default=False)),
                ('good_attitude', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_type', models.IntegerField(default=0)),
                ('service_price', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('slug', models.SlugField(blank=True)),
                ('salon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profile_image/default.jpg', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follows',
            name='salon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonrate.Salon'),
        ),
        migrations.AddField(
            model_name='follows',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
