# Generated by Django 2.1.5 on 2022-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
