# Generated by Django 2.1.5 on 2022-03-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonrate', '0002_auto_20220303_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='service_id',
        ),
    ]
