# Generated by Django 2.1.5 on 2022-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonrate', '0003_auto_20220303_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='salon_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='service_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='salon_or_service_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
