# Generated by Django 2.1.5 on 2022-03-17 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonrate', '0004_auto_20220303_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name_plural': 'Follows'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='salon',
            old_name='salon_rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='tag',
        ),
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='salon',
            name='cost_effective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='good_attitude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='good_env',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='good_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='good_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, default='salon_image/default.jpg', upload_to='salon_image'),
        ),
        migrations.AddField(
            model_name='salon',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', upload_to='profile_image'),
        ),
    ]
