# Generated by Django 2.1.5 on 2022-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonrate', '0005_auto_20220317_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='unkown', max_length=128),
        ),
    ]
